site_name: Conversational Components Docs 
nav:
  - Home: index.md
  #- Tutorials:
  #    - How to integrate a component with RASA: tutorials/rasa.md
  - Video Tutorials: tutorials/videos.md
  - SDKs: SDKs.md
  - API Spec: api.html

theme: material
